export const NEWS_ARTICLES = [
  {
    id: "n1",
    title: "Pike Place Market Announces Fall Vendor Lineup",
    category: "Local",
    date: "2026-09-18",
    photo: "/img/news/news-1.jpg",
    excerpt: "Dozens of new local farmers and makers join the historic market ahead of the holiday season, with an emphasis on Washington-grown produce and small-batch goods.",
    body: "Dozens of new local farmers and makers join the historic market ahead of the holiday season, with an emphasis on Washington-grown produce and small-batch goods. Market management says foot traffic is already up compared to last fall, and a new weekend music series kicks off this Saturday near the main arcade.",
  },
  {
    id: "n2",
    title: "Downtown Seattle Sees Surge in Weekend Foot Traffic",
    category: "Business",
    date: "2026-09-16",
    photo: "/img/news/news-2.jpg",
    excerpt: "New retail openings and a busy events calendar are drawing more visitors back downtown, according to a report from the Seattle Metro Chamber.",
    body: "New retail openings and a busy events calendar are drawing more visitors back downtown, according to a report from the Seattle Metro Chamber. Several storefronts that sat empty for over a year have new tenants, and local business owners say the mood is cautiously optimistic heading into Q4.",
  },
  {
    id: "n3",
    title: "City Council Reviews Waterfront Redevelopment Timeline",
    category: "City Hall",
    date: "2026-09-14",
    photo: "/img/news/news-3.jpg",
    excerpt: "The next phase of the Seattle waterfront project is on track for an early-2027 groundbreaking, officials confirmed at Tuesday's council session.",
    body: "The next phase of the Seattle waterfront project is on track for an early-2027 groundbreaking, officials confirmed at Tuesday's council session. The plan includes an expanded pedestrian promenade, additional green space, and improved ferry terminal access.",
  },
  {
    id: "n4",
    title: "Rainy Week Ahead as Fall Weather Pattern Sets In",
    category: "Weather",
    date: "2026-09-13",
    photo: "/img/news/news-4.jpg",
    excerpt: "After a dry stretch, the Pacific Northwest's classic fall drizzle returns Thursday, with periodic showers expected through the weekend.",
    body: "After a dry stretch, the Pacific Northwest's classic fall drizzle returns Thursday, with periodic showers expected through the weekend. Meteorologists say temperatures will stay mild, hovering in the low 60s, typical for late September in the Seattle area.",
  },
  {
    id: "n5",
    title: "Kerry Park Viewpoint Gets a Small Facelift",
    category: "Local",
    date: "2026-09-11",
    photo: "/img/news/news-5.jpg",
    excerpt: "Parks and Recreation crews repaved the popular overlook path and added new signage pointing out Seattle's skyline landmarks.",
    body: "Parks and Recreation crews repaved the popular overlook path and added new signage pointing out Seattle's skyline landmarks. The viewpoint remains one of the most photographed spots in the city, especially at sunset.",
  },
  {
    id: "n6",
    title: "Local Coffee Roasters Team Up for Neighborhood Crawl",
    category: "Community",
    date: "2026-09-09",
    photo: "/img/news/news-8.jpg",
    excerpt: "Eight independent roasters across Capitol Hill and Ballard are hosting a joint tasting event next weekend, with proceeds going to a local food bank.",
    body: "Eight independent roasters across Capitol Hill and Ballard are hosting a joint tasting event next weekend, with proceeds going to a local food bank. Tickets include a passport-style card stamped at each stop.",
  },
  {
    id: "n7",
    title: "Light Rail Extension Construction Reaches Halfway Point",
    category: "Transit",
    date: "2026-09-07",
    photo: "/img/news/news-9.jpg",
    excerpt: "Sound Transit crews say the northern extension is now roughly 50% complete, with service still targeted for 2028.",
    body: "Sound Transit crews say the northern extension is now roughly 50% complete, with service still targeted for 2028. Riders can expect intermittent weekend closures on connecting bus routes through the fall as work continues.",
  },
  {
    id: "n8",
    title: "New Food Truck Row Opens Near South Lake Union",
    category: "Food",
    date: "2026-09-05",
    photo: "/img/news/news-10.jpg",
    excerpt: "A dozen local vendors have set up a permanent weekday lunch spot, filling a gap for the neighborhood's growing office workforce.",
    body: "A dozen local vendors have set up a permanent weekday lunch spot, filling a gap for the neighborhood's growing office workforce. The lineup rotates seasonally and includes several AllSeattle-listed businesses.",
  },
  {
    id: "n9",
    title: "Neighborhood Watch Groups Report Quiet Summer",
    category: "Safety",
    date: "2026-09-03",
    photo: "/img/news/news-6.jpg",
    excerpt: "Community safety volunteers across several districts say minor incident reports are down compared to last year.",
    body: "Community safety volunteers across several districts say minor incident reports are down compared to last year. Organizers credit better street lighting and more consistent neighborhood patrols.",
  },
  {
    id: "n10",
    title: "Tech District Office Vacancies Start to Shrink",
    category: "Business",
    date: "2026-09-01",
    photo: "/img/news/news-11.jpg",
    excerpt: "After several slow years, commercial leasing agents report renewed interest in mid-size office space near the tech corridor.",
    body: "After several slow years, commercial leasing agents report renewed interest in mid-size office space near the tech corridor. Several smaller companies are opting for flexible, shorter-term leases.",
  },
];
