export const NEWS_ARTICLES = [
  {
    id: "n1",
    title: "Ballard's Newest Bakery Is Already Selling Out by 9 a.m.",
    category: "Food",
    author: "Priya Nair",
    publishedAt: "2026-09-23T07:45:00",
    photo: "img/news/news-1.jpg",
    excerpt: "Fremont Rise Bakery's second location on Ballard Avenue sold through its entire sourdough batch in under two hours on opening day.",
    body: "Fremont Rise Bakery's second location on Ballard Avenue sold through its entire sourdough batch in under two hours on opening day. Owner Dana Kwon says the Ballard shop will add a second oven by October to keep up with demand. Regulars from the original Fremont location have already started making the trip north for the cardamom knots.",
  },
  {
    id: "n2",
    title: "Cal Anderson Park's West Lawn Reopens After Six-Month Drainage Project",
    category: "City Hall",
    author: "Maria Chen",
    publishedAt: "2026-09-23T05:20:00",
    photo: "img/news/news-2.jpg",
    excerpt: "Seattle Parks says a new subsurface drainage system should finally keep the field usable through the rainy season.",
    body: "Cal Anderson Park's west lawn reopened to the public this week after a six-month project to fix chronic drainage problems that turned the field to mud every winter. Seattle Parks and Recreation says the new subsurface drainage system should keep the lawn usable through the rainy season for the first time in years. The renovation also added two new benches near the reservoir and repaved a stretch of the path connecting to 11th Avenue. Neighbors who organized a petition over the standing water back in 2024 say they're relieved but want the city to commit to regular maintenance. The splash pad on the east side of the park is unaffected and will run through the end of the month.",
  },
  {
    id: "n3",
    title: "Fremont Oktoberfest Returns This Weekend With a New Beer Garden Layout",
    category: "Community",
    author: "Sofia Reyes",
    publishedAt: "2026-09-22T20:10:00",
    photo: "img/news/news-3.jpg",
    excerpt: "Organizers added a second entrance and expanded seating under the Aurora Bridge to ease last year's long lines.",
    body: "Fremont Oktoberfest returns to N 34th Street this weekend with a redesigned beer garden meant to ease last year's long lines at the gate. Organizers added a second entrance off Phinney Avenue and expanded seating under the Aurora Bridge. More than 20 local breweries are pouring this year, including a few new additions from South Park and Georgetown.",
  },
  {
    id: "n4",
    title: "Sound Transit Opens Comment Period on Ballard Link Station Design",
    category: "Transit",
    author: "Tom Whitfield",
    publishedAt: "2026-09-22T09:00:00",
    photo: "img/news/news-4.jpg",
    excerpt: "Three station design concepts are up for public comment ahead of an open house at the Ballard branch library.",
    body: "Sound Transit is asking for public input on three design concepts for the future Ballard Link light rail station, with an open house scheduled at the Ballard branch library next month. The proposals differ mainly in where the station entrance would sit relative to 15th Avenue NW and how much surface parking would be removed. Agency planners say construction isn't expected to start until at least 2029, but they want feedback locked in early. Written comments are being accepted online through the end of October.",
  },
  {
    id: "n5",
    title: "First Atmospheric River of the Season Expected This Weekend",
    category: "Weather",
    author: "Jasmine Cole",
    publishedAt: "2026-09-21T16:30:00",
    photo: "img/news/news-5.jpg",
    excerpt: "The season's first sustained heavy rain is forecast to move into the region Saturday night.",
    body: "A plume of moisture is forecast to move into the Puget Sound region Saturday night, bringing the season's first sustained heavy rain and gusty wind to the coast and interior lowlands alike. The National Weather Service says isolated areas could see over two inches of rain by Monday morning.",
  },
  {
    id: "n6",
    title: "West Seattle Bridge Inspection Finds No New Cracking, SDOT Says",
    category: "Local",
    author: "Sofia Reyes",
    publishedAt: "2026-09-20T11:00:00",
    photo: "img/news/news-6.jpg",
    excerpt: "SDOT's latest inspection found no new cracking since the bridge reopened in 2022.",
    body: "The Seattle Department of Transportation's latest structural inspection of the West Seattle Bridge found no new cracking since repairs were completed in 2022. The bridge is inspected on a rolling schedule as part of the long-term monitoring plan put in place after the closure.",
  },
  {
    id: "n7",
    title: "Occidental Square Packed Before Sounders Match at Lumen Field",
    category: "Sports",
    author: "Marcus Bell",
    publishedAt: "2026-09-19T18:45:00",
    photo: "img/news/news-7.jpg",
    excerpt: "Vendors along Occidental Avenue reported some of their busiest foot traffic of the season.",
    body: "Occidental Square was standing room only two hours before kickoff Saturday as Sounders fans gathered in the fan zone before walking down to Lumen Field. Vendors along Occidental Avenue reported some of their busiest foot traffic of the season.",
  },
  {
    id: "n8",
    title: "Wallingford Ramen Shop Adds Seating After a TikTok Video Went Viral",
    category: "Business",
    author: "Derek Alvarez",
    publishedAt: "2026-09-18T08:00:00",
    photo: "img/news/news-8.jpg",
    excerpt: "Owner Kevin Tran says weekend wait times had stretched past 90 minutes before the expansion.",
    body: "Fremont Bowl, a small ramen counter on N 45th Street, knocked down a storage wall last week to add eight more seats after a video of its tonkotsu broth passed two million views on TikTok. Owner Kevin Tran says weekend wait times had stretched past 90 minutes. He's now looking at a second location, possibly in Phinney Ridge.",
  },
  {
    id: "n9",
    title: "SPD Hosts Public Safety Q&A in the Chinatown-International District",
    category: "Safety",
    author: "Hana Kobayashi",
    publishedAt: "2026-09-16T14:00:00",
    photo: "img/news/news-9.jpg",
    excerpt: "About 40 residents and business owners turned out to a community session at Hing Hay Park.",
    body: "The Seattle Police Department's West Precinct held a community question-and-answer session at Hing Hay Park Tuesday evening, fielding questions about foot patrol frequency and lighting along South Jackson Street. About 40 residents and business owners attended.",
  },
  {
    id: "n10",
    title: "Overlook Walk at the Waterfront Park Opens to the Public",
    category: "City Hall",
    author: "Maria Chen",
    publishedAt: "2026-09-14T10:00:00",
    photo: "img/news/news-10.jpg",
    excerpt: "The pedestrian bridge connecting Pike Place Market to the waterfront park opened this week after years of construction.",
    body: "The Overlook Walk, the pedestrian bridge connecting Pike Place Market to the new waterfront park, opened to the public this week after years of construction tied to the Alaskan Way Viaduct replacement. The terraced walkway includes a new play area, a small amphitheater, and unobstructed views of Elliott Bay from above the seawall. City officials held a short ribbon-cutting Tuesday morning, though the space had already drawn crowds over the weekend before the official opening. The final phase of landscaping along the promenade is expected to wrap by early next year.",
  },
  {
    id: "n11",
    title: "Ballard Farmers Market Vendors Call It the Best Tomato Season in Years",
    category: "Community",
    author: "Priya Nair",
    publishedAt: "2026-09-11T09:30:00",
    photo: "img/news/news-11.jpg",
    excerpt: "A warm, dry August produced some of the best heirloom tomatoes local growers have seen in a decade.",
    body: "Vendors at the Sunday Ballard Farmers Market say this year's warm, dry stretch in August produced some of the best heirloom tomatoes they've seen in a decade. Several stalls sold out by 11 a.m. two weekends in a row.",
  },
  {
    id: "n12",
    title: "Georgetown's Art Attack Brings Pop-Up Galleries to Airport Way",
    category: "Community",
    author: "Marcus Bell",
    publishedAt: "2026-09-08T15:00:00",
    photo: "img/news/news-12.jpg",
    excerpt: "More than a dozen studios along Airport Way South will open for the free self-guided walk Saturday night.",
    body: "Georgetown's monthly Art Attack returns Saturday night, with more than a dozen studios and pop-up galleries along Airport Way South opening their doors for the free self-guided walk. Several spaces are showing new work for the first time since summer.",
  },
];
